### ISSUE TITLE
Why -s after each task?

### ISSUE THREAD

**Issue by twalker** [keithamus/npm-scripts-example#15]
Each occurrence of `npm run` is passed a `-s` argument.
What purpose does this serve?

Thank you

**Comment by keithamus** [comment]
It silences npms output from the subtasks, which makes the log output a little tidier (it is a shortcut for `--loglevel=silent`. It is not necessary. Remove it to see the difference!

**Comment by twalker** [comment]
Great, thanks. 
And thank you for enlightening me with npm scripts.
