### ISSUE TITLE
-s option in the lines like npm run clean -s, npm run build:scripts -s, etc - what does that signify.

### ISSUE THREAD

**Issue by henns20** [keithamus/npm-scripts-example#16]
What does that option mean in that context? Is it a fish command line related option? Does it mean to 'read as a stndin' ? That is the only thing that I can not find - and it was in the bash ref manual. Thx

**Comment by keithamus** [comment]
See https://github.com/keithamus/npm-scripts-example/issues/15

> It silences npms output from the subtasks, which makes the log output a little tidier (it is a shortcut for `--loglevel=silent`. It is not necessary. Remove it to see the difference!

**Comment by henns20** [comment]
Okay docs are obscure or access to it was confusing for me getting familiar npm scripts, etc- finally found it in the  docs using `npm help 7 npm-config` in terminal. Thanks and you answered this right as I was typing what I found. Thank you for the response.
