### ISSUE TITLE
Fix for Windows DOS, PowerShell, GitBash, etc. (single vs. double quote paths)

### ISSUE THREAD

**Issue by danielweck** [keithamus/npm-scripts-example#17]
Fixed in `build:scripts` and `build:styles` by replacing:

`'dist/{name}{hash}{ext}'`

with:

`\"dist/{name}{hash}{ext}\"`

Related issue: https://github.com/keithamus/npm-scripts-example/issues/5

**Comment by danielweck** [comment]
PS: I'm also using `watch` instead of `nodemon`:
```
"watch1:build": "nodemon -q -w assets/ --ext '.' --exec \"npm run build\"",
"watch2:build": "watch \"npm run build\" assets/"
```

**Comment by jez9999** [comment]
Doublequotes works on Linux too (I just tried it out), so they should be used for the `package.json` to build in a cross-platform way.
