### ISSUE TITLE
Wild card path with ** does not seems to be working for a lot of tools

### ISSUE THREAD

**Issue by sunshineo** [keithamus/npm-scripts-example#18]
For example, I have this in grunt using grunt-jshint:
<pre>
    jshint: {
			all: {
				src: ["www/modules/**/*.js"],
				options: {
					jshintrc: true
				}
			}
		}
</pre>
However when I try to run the tool installed by `npm install jshint` , it does not work when using this line
`./node_modules/jshint/bin/jshint www/modules/**/*.js`
It does not run on any file at all.

**Comment by sunshineo** [comment]
Anyone can help? This blocker will make me stay using grunt.

**Comment by keithamus** [comment]
You need to enable globstar in bash - not all bashes come equipped with it. Run `shopt -s globstar` in your terminal to fix it.

Alternatively, pass jshint a folder, e.g. `jshint www/modules/` and it'll recurse through them, finding all JS files and linting them. If you want it to ignore some files, you can set up a `.jshintignore` files; see http://stackoverflow.com/questions/12977661/is-there-a-way-to-suppress-jshint-warning-for-one-given-line http://jshint.com/docs/ for more, or https://github.com/jquery/jquery/blob/master/.jshintignore as an example.

**Comment by sunshineo** [comment]
Thank you @keithamus , I'll try these and report back.

**Comment by sunshineo** [comment]
@keithamus Passing the folder works. I'll use that. Thank you very much!

**Comment by keithamus** [comment]
:+1:
