### ISSUE TITLE
using node-sass

### ISSUE THREAD

**Issue by hartey11** [keithamus/npm-scripts-example#19]
Hi,

how would you setup to use sass instead of stylus?

Thanks

**Comment by keithamus** [comment]
Hey @hartey11 thanks for the issue.

It should be pretty easy to switch over to node-sass, at the moment the `build:styles` command has the following inside of it:

```js
stylus assets/styles/main.styl -m -o dist/
```

To do the same in Node Sass, we can look at the [binary usage docs](https://github.com/sass/node-sass#usage-1) and we get almost the same command back:

```js
node-sass assets/styles/main.scss --source-map -o dist/
```

Then it's just a case of simply swapping the dependencies around. I'll leave the rest to you :smile:
