### ISSUE TITLE
Passing arguments within a script

### ISSUE THREAD

**Issue by reggi** [keithamus/npm-scripts-example#2]
Any idea how I'd replace all instances of `breaknotes` in this script with a argument?

I'm very close to writing a build script to write build scripts for each of my components. (not a good idea)

```
`scripts`:{
    "update:breaknotes": "cd ./generators/ && node component.js breaknotes && terminal-notifier -message 'breaknotes updated'",
}
```

sadly `npm config set component "breaknotes` doesn't update the local package config even without the --global flag. `$npm_package_config_component` only pulls in the local 

```
  "config": {
    "component": "breaknotes"
  },
```

Is there a way to write to the local config with a command because then we could write

```
npm config set component "breaknotes" && npm run update:component
```

**Comment by cachaito** [comment]
I hope @keithamus and @reggi  won't mind If link in to this question. I have problem with understanding `$npm_package_config_component`. [In the article](http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/) @keithamus wrote:
> the npm run test command uses the $npm_package_config_mocha_reporter variable which gets expanded to mocha test/ --reporter xunit

But in my `server.js` script
```
"config": {
    "CHANNEL": "test"
},
"scripts": {
    "serve:json": "node env/server.js $npm_package_config_CHANNEL"
}
```
console.log of `process.argv` shows not evaluated string: 
```
[ 'node',
  'd:\\Projekty\\Minefield\\table_app_mithril\\env\\server.js',
  '--someFlag',
  '$npm_package_config_CHANNEL' ]
```

**Comment by reggi** [comment]
@cachaito  It seems to be working just fine for me using the following `package.json` and the commands `npm run example` & `npm run caps` & `npm run arg`. Note I'm on version `npm@2.7.5`, make sure your up to date.

```
{
  "name": "example",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "config":{
    "var": "hello world",
    "VAR": "HELLO WORLD"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "example": "echo $npm_package_config_var",
    "caps": "echo $npm_package_config_VAR",
    "arg": "node -e 'console.log(process.argv)' $npm_package_config_var $npm_package_config_VAR"
  },
  "author": "",
  "license": "ISC"
}
```

**Comment by cachaito** [comment]
Hi @reggi! Thank You for response. Unfortunately Your code doesn't work as expected on my machine: `Windows 7 64bit`, `npm@2.7.4`, `NodeJS v0.12.2`

For example example task outputs:
```
$ npm run example

> table_app_mithril@0.0.2 example D:\Projekty\Minefield\table_app_mithril
> echo $npm_package_config_var

$npm_package_config_var
```
:sob:

**Comment by keithamus** [comment]
Ah, unfortunately variables won't work in Windows. You can use npm config still, but you have to use it inside of a Node.js script, so this will work:

```json
{
  "name": "example",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "config":{
    "var": "hello world",
    "VAR": "HELLO WORLD"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "example": "node -p 'process.env.npm_package_config_var'",
    "caps": "node -p 'process.env.npm_package_config_VAR'"
  },
  "author": "",
  "license": "ISC"
}
```

Alternatively if you're ONLY using windows for this project, you can use the Windows variable syntax of `%VAR%`. I haven't tested this but it should work:

```json
{
  "name": "example",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "config":{
    "var": "hello world",
    "VAR": "HELLO WORLD"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "example": "echo %npm_package_config_var%",
    "caps": "echo %npm_package_config_VAR%",
    "arg": "node -e 'console.log(process.argv)' %npm_package_config_var% %npm_package_config_VAR%"
  },
  "author": "",
  "license": "ISC"
}
```

**Comment by cachaito** [comment]
Big thank for this explanation @keithamus! Now it's clear :open_mouth:
By the way: Thank You - Windows  :disappointed:
