### ISSUE TITLE
Problematic font families

### ISSUE THREAD

**Issue by mpal9000** [keithamus/npm-scripts-example#28]
Hello, I couldn't find a better place to post this. There is a problem with "Fira Mono" and "Fira Sans" font families in http://blog.keithcirkel.co.uk/.

See also https://github.com/facebook/immutable-js/issues/468

**Comment by keithamus** [comment]
Hmm that sucks. What operating system are you using? Do you have the fonts already installed in your OS?

**Comment by mpal9000** [comment]
I'm using Arch Linux and the fonts seem to be installed:

$ fc-list | grep -i "Fira"
/usr/share/fonts/TTF/FiraMono-Bold.ttf: Fira Mono:style=Bold
/usr/share/fonts/TTF/FiraSans-BoldItalic.ttf: Fira Sans:style=Bold Italic
/usr/share/fonts/TTF/FiraSans-Light.ttf: Fira Sans,Fira Sans Light:style=Light,Regular
/usr/share/fonts/TTF/FiraSans-Bold.ttf: Fira Sans:style=Bold
/usr/share/fonts/TTF/FiraMono-Regular.ttf: Fira Mono:style=Regular
/usr/share/fonts/TTF/FiraSans-Medium.ttf: Fira Sans,Fira Sans Medium:style=Medium,Regular
/usr/share/fonts/TTF/FiraSans-LightItalic.ttf: Fira Sans,Fira Sans Light:style=Light Italic,Italic
/usr/share/fonts/TTF/FiraSans-Regular.ttf: Fira Sans:style=Regular
/usr/share/fonts/TTF/FiraSans-MediumItalic.ttf: Fira Sans,Fira Sans Medium:style=Medium Italic,Italic
/usr/share/fonts/TTF/FiraMono-Medium.ttf: Fira Mono,Fira Mono Medium:style=Medium,Regular
/usr/share/fonts/TTF/FiraSans-Italic.ttf: Fira Sans:style=Italic

**Comment by mpal9000** [comment]
https://github.com/google/fonts/issues/10

**Comment by mpal9000** [comment]
problem solved with the latest ttf-google-fonts
