### ISSUE TITLE
Add text banner to output file.

### ISSUE THREAD

**Issue by koskh** [keithamus/npm-scripts-example#31]
Hi. If you want to add banner to output file, you could make  the following.

1 make helper ( `add-banner.js` for example)

```
var pckgJson = require(process.env.PWD +'/package.json');
var banner = '/* ' + pckgJson.name + ' - '+ pckgJson.config.banner +' - ' + new Date() + ' */\n';

process.stdout.write(banner);
process.stdin.pipe(process.stdout);
```

2 Add  data into `config`

```
 "config": {
    "banner": " ...Header banner text ... "
  }
```

3 Add into `scripts`

```
"build:css": "node-sass ./style/index.scss | node ./utils/build/add-banner.js > ./build/index.css"
```

**Comment by francoismassart** [comment]
How is this an issue ?

**Comment by keithamus** [comment]
Its not an issue - but its a great tip! Perhaps @koskh could make a PR to add a `tips.md` with this kind of info?

**Comment by francoismassart** [comment]
[This tip has been documented](https://github.com/keithamus/npm-scripts-example/blob/master/tips/add-text-banner-to-output-file.md) and you can also see the changes made for a demo on its dedicated branch `tips/add-text-banner-to-output-file`

Change log inside this commit: https://github.com/keithamus/npm-scripts-example/commit/a9a35400a9ff00e9190a7397019fc6b27a27906e
