### ISSUE TITLE
Example with watchify/browserify using glob?

### ISSUE THREAD

**Issue by Kiura** [keithamus/npm-scripts-example#34]
Hello, Keith Cirkel!
I read your article and it is second time I am trying to set up npm instead of gulp (moved to gulp from grunt). My problem is that I cant set up npm to watch several files and output several files (which I can do using gulp): 
```javascript

gulp.task('es6',function (done) {
	glob('./public/js/*.js', function(err, files) {
        if(err) done(err);

        var tasks = files.map(function(entry) {
            return browserify({ entries: [entry] })
				.transform(babelify)
                .bundle()
                .pipe(source(entry))
                .pipe(rename(function (path) {
					path.dirname = "final";
				}))
                .pipe(gulp.dest('./public/js/'));
            });
        es.merge(tasks).on('end', done);
    })
});
```
Could you give me any hints?

**Comment by Kiura** [comment]
I would be grateful if you could help me setup the project (if I fail to do so)
Basically what I am doing now with gulp:
Transpile files from es6 to es2015 and browserify (using watchify) -> minify;
Compile stylus to css -> autoprefix -> minify
the structure is as follows:
```
public/
|---js/
    |---es6/
        |---classes/
        |---index.js
        |---login.js
    |---js/
        |---// place for transpiled/browserified/minified index,js and login.js
|---styles
     |---styl
        |---// similar to js structure
     |---css
        |---// similar to js structure
```
Any help highly appreciated

**Comment by keithamus** [comment]
If you want separate bundles for each page, you can do this as an npm script, using something like [multi-browserify](https://www.npmjs.com/package/multi-browserify).

```bash
multi-browserify -i ./public/js/*.js -o ./public/js/js/
```

**Comment by Kiura** [comment]
Thx for fast reply! 
This solves the problem, however, [globify](https://www.npmjs.com/package/globify) IMO is a better choice since solves several problems at once: it watchifies / uglifyifies and browserifies the files
```javascript 
globify -g uglifyify 'public/js/es6/*.js' -w -v -o 'public/js/js'```

**Comment by keithamus** [comment]
Very nice! Good call!

**Comment by Kiura** [comment]
@keithamus, Hi again, sorry to bother you again ))
```json
{
"stylus": "stylus public/styles/styl/*.styl -w --out public/styles/css",
"poststylus": "cssnano public/styles/css/*.css public/styles/css/min",
}
```
stylus works but cssnano wont, and could you give me examples of the modules I used, how to pipe the output to next one or how to optimise...

**Comment by keithamus** [comment]
Looks like cssnano doesn't come with a bin, which is a bit sad to see. You can use [postcss-cli](https://github.com/code42day/postcss-cli) instead:

```json
{
"stylus": "stylus public/styles/styl/*.styl -w --out public/styles/css",
"poststylus": "postcss-cli -u cssnano -d public/styles/css/min public/styles/css/*.css",
}
```

If you're feeling brave, considering you're using the `postcss-cli` you could just drop stylus and use [postcss](https://github.com/postcss/postcss) for everything:

```json
{
"css": "postcss-cli -u precss -u autoprefixer -u short -u <more plugins> -u cssnano -d public/styles/css/min public/styles/css/*.css",
}
```

**Comment by Kiura** [comment]
Managed somehow to set up the environment. Hope it will work fast on large files as well, thx ))

**Comment by Kiura** [comment]
Here is my set up if anyone is interested:
```json
{
    "prestylus": "mkdir -p public/styles/css/min",
    "stylus": "stylus public/styles/styl/*.styl --out public/styles/css -w ",
    "postcss": "postcss public/styles/css/*.css -d public/styles/css/min -c compileConfig.json -w ",
    "es6": "babel public/scripts/es6/ -d public/scripts/js",
    "es6:watch": "babel public/scripts/es6/ -d public/scripts/js -w",
    "preglobify": "mkdir -p public/scripts/js/min; npm run es6",
    "globify": "globify 'public/scripts/js/*.js' -w -v -o 'public/scripts/js/min'",
    "globify:prod": "globify -g uglifyify 'public/scripts/js/*.js' -w -v -o 'public/scripts/js/min'",
    "build": "parallelshell 'npm run es6:watch' 'npm run globify' 'npm run stylus' 'npm run postcss' 'node server.js'"
}
also would be great if it could be optimised

**Comment by keithamus** [comment]
Hey, so here's a cool thing! `npm run` has some nifty little tricks up it's sleeve. For example:

```js
# `npm run env` just outputs your environment variables - just to demonstrate the magic:
$ npm run env | grep NODE_ENV
$ npm run env --production | grep NODE_ENV
NODE_ENV=production
$ npm run env | grep watch
$ npm run env --watch | grep watch
npm_config_watch=true
# Actually the --watch one is just any unrecognised flag:
npm run env --foo | grep foo
npm_config_foo=true
npm run env --foo=bar | grep foo
npm_config_foo=bar
```

So if you use the `--production` flag - it'll set NODE_ENV to production. If you use the `--watch` flag it'll set `npm_config_watch` to true. We can use this to replace a few of your scripts. Let's test it out:


```json
{
  "example": "echo foo $([ $npm_config_watch ] && echo bar) baz",
  "prodexample": "echo foo $([ \"$NODE_ENV\" = 'production' ] && echo bar) baz"
}
```
```bash
$ npm run example
foo baz
$ npm run example --watch
foo bar baz

$ npm run prodexample
foo baz
$ npm run prodexample --production
foo bar baz
```

---

Another tip - `npm-run-all` is cooler than `parallelshell` because it lets you use globs to run scripts, so you can run `npm run build:*` and it'll run anything prefixed with `build:`.

---

With these two cool facts, let's try to redo your package.json:

```json
"scripts": {
    "build": "npm-run-all --parallel build:*",
    "prebuild:css": "mkdir -p public/styles/css/min",
    "build:css": "stylus public/styles/styl/*.styl --out public/styles/css $([ $npm_config_watch ] && echo -w)",
    "postbuild:css": "postcss public/styles/css/*.css -d public/styles/css/min -c compileConfig.json",
    "prebuild:js": "mkdir -p public/scripts/js/min",
    "build:js": "globify 'public/scripts/es6/*.js' $([ \"$NODE_ENV\" = 'production' ] && echo -g uglifyify) -t babelify -vo 'public/scripts/js/min' $([ $npm_config_watch ] && echo -w)",
},
```

Some of the lines are a little long, which is a shame - but on the plus side you have some simple commands:

```sh
$ npm run build # build all JS
$ npm run build --watch # build all JS and watch for changes
$ npm run build --production # build all JS and minify it all
$ npm run build --production --watch # build all JS and minify, and watch for changes
```

**Comment by Kiura** [comment]
That seems really cool and package.json looks clearer, however, I cant get it work...
changed a little bit the package.json (corrected typo -vo to -o in build:js and added start task)
```json
"scripts": {
  	"start": "node server.js",
    "build": "npm-run-all --parallel build:* --sequential start",
    "prebuild:css": "mkdir -p public/styles/css/min",
    "build:css": "stylus public/styles/styl/*.styl --out public/styles/css $([ $npm_config_watch ] && echo -w)",
    "postbuild:css": "postcss public/styles/css/*.css -d public/styles/css/min -c compileConfig.json",
    "prebuild:js": "mkdir -p public/scripts/js/min",
    "build:js": "globify 'public/scripts/es6/*.js' $([ \"$NODE_ENV\" = 'production' ] && echo -g uglifyify) -t babelify -o 'public/scripts/js/min' $([ $npm_config_watch ] && echo -w)"
  },
```
And thanks for all help and time really appreciate it ))

**Comment by keithamus** [comment]
Yeah I guess if you add `--watch` then `postbuild:css` will never get to execute, because you use <kbd>Ctrl</kbd><kbd>C</kbd> to exit...

I think the only way around this is to remove the postbuild:css task. Or to wrap the stylus and postcss commands into a separate watcher - but that would be very messy and not very well optimized.

**Comment by Kiura** [comment]
I see, will go back using the one that worked for me, and close this issue, thx again
