### ISSUE TITLE
Made a tool to use JS with npm scripts

### ISSUE THREAD

**Issue by corysimmons** [keithamus/npm-scripts-example#38]
https://github.com/corysimmons/package-script-manager

Sorry if this is the wrong place (don't want to have to get a Twitter account and couldn't find your email anywhere) but wanted to ping you about this thing since "JSON is restrictive" is the biggest drawback of npm scripts.

This seems to fix it. Let me know what you think and if you think of any cool ways to use it.

**Comment by francoismassart** [comment]
See https://github.com/keithamus/npm-scripts-example/commit/7202006044e5c2ac222f0f6451d12dbd9ca1ded9

**Comment by corysimmons** [comment]
@francoismassart Sorry, forgot about this. I think https://github.com/kentcdodds/nps is probably a better option as it's maintained by some high profile people and does essentially the same thing as my unmaintained package.
