### ISSUE TITLE
migrate from Gulp

### ISSUE THREAD

**Issue by gerardolima** [keithamus/npm-scripts-example#39]
Hi, guys,

I'm doing a painful migration from Grunt to Gulp. Not that I miss, Grunt (not at all!), but all **js**/**ts** and **css**/**scss** file traversing _feels_ unnatural with glob patterns. Therefore, I rely on Sass and Browserify to safely build my bundles and my build process is actually _done_ by them -- both these tools also provide _watch_ functionality! So, I'm left with very few _ups_ on having Grulp, or whatever other task runner.

O the other way, though, my dev and build environments are windows and it also feels awkward to use old CMD syntax, so, what would you suggest? I also found the [npm-build-tools](https://github.com/Deathspike/npm-build-tools) on the Npm registry and it seems to overcome some differences between Win and bash; is it a good/recommended approach?

thank you in advance!

**Comment by patkujawa-wf** [comment]
You might not need a separate build tool once you read https://www.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/ :)

**Comment by gerardolima** [comment]
Thank you, @patkujawa-wf, I had already read that article. My doubts are regarding having inconsistent scripting between dev machines (windows) and CI tools in linux environment, for example.

**Comment by gmmedia** [comment]
@gerardolima Do you use now the new Linux subsystem in Windows 10? It's great.

**Comment by gerardolima** [comment]
@gmmedia I changed the shell interpreter in npm to use bash; it "feels" unnatural, but solved my problem.
