### ISSUE TITLE
Livereload doesn't work correctly

### ISSUE THREAD

**Issue by miloskroulik** [keithamus/npm-scripts-example#6]
Livereload doesn't work correctly on my Ubuntu 14.04 install. After editing index.jade the page reloads, but instead of updated file, there's only directory index with link to .gitkeep file displayed. Am I doing something wrong? It looks like the livereload should wait for page to regenerate, but it doesn't.

**Comment by mhulse** [comment]
From what I can tell, LifeReload reloads before the build finishes; this is why you get a default server index view. If you do a manual refresh after the build finishes, then the page will appear.

I'm not certain, but there does not appear to be a "wait" command line option for [node-live-reload](https://github.com/rowoot/node-live-reload).

In SublimeText, using Grunt and the LiveReload plugin, I'd set the wait time for LiveReload to fire; this time would be a few hundred MS longer than an average build time.

**Comment by matt-basedin** [comment]
I am also running into this issue. If there are any tips on how to fix this then that would be awesome!

**Comment by wifiextender** [comment]
Fuck any **reloading** script !

Here's auto-reloading dead simple 1 liner script that auto-reloads the current page every 2 seconds.

```javascript
<script type="text/javascript">
    setInterval(function() {
        window.location.reload();
    },
    2000);
</script>
```

**Comment by francoismassart** [comment]
👍 
Indeed, from time to time, while using `npm run dev` I get the index list from time to time.

**Comment by francoismassart** [comment]
It seems that the `=` is required for the parameters of `live-reload` !

PR is on its way.

**Comment by francoismassart** [comment]
Hi there,
please let me know if you still get the issue after this fix.

Do not forget to run `npm install` in order to get the latest version of `live-reload` too.
